-- Eliminar tablas si existen
DROP TABLE IF EXISTS NOTIFICATION_VIEWS;

DROP TABLE IF EXISTS NOTIFICATIONS;

-- Crear tabla de notificaciones
CREATE TABLE IF NOT EXISTS NOTIFICATIONS (
    ID SERIAL PRIMARY KEY,
    MESSAGE TEXT NOT NULL,
    TIMESTAMP TIMESTAMP NOT NULL DEFAULT NOW(),
    CREATED_BY_ID INTEGER NOT NULL,
    CREATED_BY_NAME VARCHAR(100) NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'active'
);

-- Crear tabla de visualizaciones de notificaciones
CREATE TABLE IF NOT EXISTS NOTIFICATION_VIEWS (
    ID SERIAL PRIMARY KEY,
    NOTIFICATION_ID INTEGER NOT NULL,
    USER_ID INTEGER NOT NULL,
    VIEWED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    FOREIGN KEY (NOTIFICATION_ID) REFERENCES NOTIFICATIONS(ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE
);

-- Crear índices para mejorar el rendimiento
CREATE INDEX IF NOT EXISTS IDX_NOTIFICATIONS_STATUS ON NOTIFICATIONS(STATUS);

CREATE INDEX IF NOT EXISTS IDX_NOTIFICATION_VIEWS_NOTIFICATION_ID ON NOTIFICATION_VIEWS(NOTIFICATION_ID);

CREATE INDEX IF NOT EXISTS IDX_NOTIFICATION_VIEWS_USER_ID ON NOTIFICATION_VIEWS(USER_ID);